### ISSUE TITLE
The compiler is running out of heap space

### ISSUE THREAD

**Issue by BarryLiu97** [BrainsOnBoard/procedural_paper#11]
Hi, I was running this [code](https://github.com/BarryLiu97/multi-area-model/blob/master/run_example_downscaled.py), and I encountered a problem. When I ran it, it got stuck in runner.cc, the CPU seemed still worked, and the error said
```
E:\PCL\multi-area-model\multi_area_model_CODE\runner.cc(141827): fatal error C1002: The compiler is running out of heap space on pass 2 [E:\PCL\multi-area
-model\multi_area_model_CODE\runner.vcxproj]
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.1.t
argets(764,9): error MSB3721: command “"D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=
compute_61,code=\"sm_61,compute_61\" --use-local-env -ccbin "D:\Program Files (x86)\Microsoft Visual Studio\2019\Commun
ity\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64" -x cu -rdc=true -I"D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v1
0.1\include" -I"D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"     --keep-dir x64\Release -maxrregco
unt=0  --machine 64 --compile -cudart static     -DWIN32 -DWIN64 -DNDEBUG -D_CONSOLE -DBUILDING_GENERATED_CODE -D_WINDL
L -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdx64\Release\vc142.pdb /FS /Zi  /MD " -o x64\Release\runner.cc.obj "E:\PC
L\multi-area-model\multi_area_model_CODE\runner.cc"” exited，return code 1. [E:\PCL\multi-area-model\multi_area_model_CODE\runner.
vcxproj]
Traceback (most recent call last):
  File "run_example_downscaled.py", line 46, in <module>
  File "E:\PCL\multi-area-model\multiarea_model\simulation.py", line 308, in simulate
    self.model.build()
  File "e:\pcl\procedural_paper\genn\pygenn\genn_model.py", line 517, in build
    path.join(output_path, "runner.vcxproj")])
  File "D:\ProgramData\Miniconda3\envs\pcl\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msbuild', '/p:Configuration=Release', '/m', '/verbosity:minimal', './multi_area_model_CODE\\runner.vcxproj']' returned non-zero exit status 1.
```
I Googled it and it told me to run command ```set PreferredToolArchitecture=x64``` in the terminal, which I did and it didn't work.

**Comment by neworderofjamie** [comment]
This is an interesting one. All our machines with GPUs capable of running the full-scale model use Linux so I hadn't really tried building the multi-area model on Windows before. However, I can confirm that I can reproduce this on my machine and will investigate whether there's anything we can do to fix this issue.

**Comment by BarryLiu97** [comment]
All right, thank you so much! As to Linux, it does work fine.

**Comment by neworderofjamie** [comment]
Ok, after some investigation, https://github.com/genn-team/genn/pull/407 fixes the error you found but then https://github.com/genn-team/genn/issues/408 which is going to be harder to fix. Basically, the conclusion is that models with 10s of thousands of populations can't be compiled on Windows.

**Comment by BarryLiu97** [comment]
Wow, nice. I'll have a try. For I am not good at C++, I couldn't help it, so I'll wait for your good news.
